### ISSUE TITLE
"bigScene" from vanilla checkout does not work

### ISSUE THREAD

**Issue by flberger-work** [framefield/vr-annotate#4]
After a checkout of the most recent version, loading the scene "bigScene" throws 14 warnings and 160 errors and consequently refuses to start:

    A meta data file (.meta) exists but its asset 'Assets/db/annotations' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
    A meta data file (.meta) exists but its asset 'Assets/db/targets' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
    Assertion failed: Removing Assets/db/annotations because the asset does not exist
    Assertion failed: Removing Assets/db/targets because the asset does not exist
    Assets/vendor/PunchKeyboard/Scripts/Keyboard/KeycodeAdder.cs(4,7): error CS0246: The type or namespace name `WindowsInput' could not be found. Are you missing an assembly reference?
    ...
    Assets/vr_annotate/ff.vr.interaction/VRConsole/VRConsoleTMPro.cs(4,7): error CS0246: The type or namespace name `TMPro' could not be found. Are you missing an assembly reference?
    ...
    Assets/vendor/PunchKeyboard/Scripts/Keyboard/KeycodeAdder.cs(9,12): error CS0246: The type or namespace name `VirtualKeyCode' could not be found. Are you missing an assembly reference?
    ...
    Assets/vr_annotate/ff.nodegraph.interaction/InfoPanel/AnnotationInfoPanel/AnnotationInfoPanel.cs(18,9): error CS0246: The type or namespace name `TMPro' could not be found. Are you missing an assembly reference?
    ...
    Assets/vr_annotate/ff.vr.interaction/VRConsole/VRConsoleTMPro.cs(10,12): error CS0246: The type or namespace name `TextMeshPro' could not be found. Are you missing an assembly reference?
    ...
    FreeType error: The font Assets/vendor/TextMesh Pro/Fonts/LiberationSans.ttf could not be imported because the  format is unsupported
    ...
    ImportFBX Errors: Couldn't read file C:/Users/agora/Desktop/vr-annotate-master/vr-annotate-master/Assets/vr_annotate/ff.vr.interaction/Teleportation/geometry/teleportTargetCylinder.fbx. Unexpected file type
    ...
    Could not create texture from Assets/vendor/TextMesh Pro/GUISkins/Textures/btn_AlignLeft.psd: File could not be read
    ...
    Errors during import of AudioClip Assets/vr_annotate/ff.vr.interaction/Teleportation/Sounds/Swooshing.mp3: FSBTool ERROR: Failed decoding audio clip.

The README does not specify any prerequisites or pre-run procedures necessary to run the scene.

OS: Windows 7

Unity version: 2017.2.0f3

Expected behaviour: The scene should load without errors and start up. If installations from third parties are required, the README should mention these.

Actual behaviour: The scene throws a lot of errors upon loading and does not start.

**Comment by flberger-work** [comment]
The very same errors surface in:

OS: macOS 10.12.6 Sierra

Unity version: 5.6.3p1

**Comment by flberger-work** [comment]
The same errors occur when following the instructions in https://github.com/framefield/vr-annotate/blob/master/README.md to install vr-annotator as a package in a new scene.

**Comment by mutaphysis** [comment]
Did you checkout using git-lfs?

Can you try to clone again after following https://help.github.com/articles/installing-git-large-file-storage/ ?

thanks,
Henrik

**Comment by flberger-work** [comment]
I will try again after installing lfs.

But the problem is also apparent using the GitHub zip file download which, in my understanding, should not be affected by git lfs issues.

**Comment by mutaphysis** [comment]
Sadly the zip **is** affected, I tried it myself last week. You will find plenty of 131 Byte files, these are the git-lfs references. The zip files seem to be useless with a git-lfs enabled repository. Not sure if this a setting or general github issue, I don't have admin rights on this repo. 

I added both into the README this morning.

bye,
Henrik

**Comment by flberger-work** [comment]
With LFS enabled resp. with a recent Sourcetree version the checkout works fine. The errors listed in the original report are gone.
